export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const START_EDIT_CONTACT = 'START_EDIT_CONTACT';
export const SAVE_EDITED_CONTACT = 'SAVE_EDITED_CONTACT';
export const CHANGE_EDITOR = 'CHANGE_EDITOR';
